### ISSUE TITLE
IllegalAccessError on launch from IntelliJ IDEA with OpenGL

### ISSUE THREAD

**Issue by easytarget2000** [benfry/processing4#167]
## Description
Launching a sketch from IntelliJ IDEA crashes when an OpenGL renderer is selected.

## Expected Behavior
The sketch should launch and run, as it does when I use the Processing IDE or switch to the JAVA2D renderer in my IntelliJ project. This issue also does not occur when running the same code with a Processing 3 `core.jar`. 

## Current Behavior
When I run my project, the fullscreen applet launches, flashes white for about half a second and then crashes with this stack trace:
```
java.lang.IllegalAccessError: class processing.opengl.PJOGL (in unnamed module @0x1b26f7b2) cannot access class com.jogamp.opengl.glu.GLU (in module jogl.all) because module jogl.all does not export com.jogamp.opengl.glu to unnamed module @0x1b26f7b2
	at processing.opengl.PJOGL.<init>(PJOGL.java:148)
	at processing.opengl.PGraphicsOpenGL.createPGL(PGraphicsOpenGL.java:712)
	at processing.opengl.PGraphicsOpenGL.<init>(PGraphicsOpenGL.java:569)
	at processing.opengl.PGraphics2D.<init>(PGraphics2D.java:36)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at processing.core.PApplet.makeGraphics(PApplet.java:2244)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:2323)
	at processing.core.PApplet.initSurface(PApplet.java:10803)
	at processing.core.PApplet.runSketch(PApplet.java:10766)
	at processing.core.PApplet.runSketch(PApplet.java:10922)
	at processing.core.PApplet.runSketch(PApplet.java:10928)
	at eu.ezytarget.processing.kotlin_template.PApplet.access$runSketch(PApplet.kt:11)
	at eu.ezytarget.processing.kotlin_template.PApplet$Companion.runInstance(PApplet.kt:202)
	at eu.ezytarget.processing.kotlin_template.Main$Companion.main(Main.kt:8)
	at eu.ezytarget.processing.kotlin_template.Main.main(Main.kt)
java.lang.RuntimeException: class processing.opengl.PJOGL (in unnamed module @0x1b26f7b2) cannot access class com.jogamp.opengl.glu.GLU (in module jogl.all) because module jogl.all does not export com.jogamp.opengl.glu to unnamed module @0x1b26f7b2
	at processing.core.PApplet.makeGraphics(PApplet.java:2277)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:2323)
	at processing.core.PApplet.initSurface(PApplet.java:10803)
	at processing.core.PApplet.runSketch(PApplet.java:10766)
	at processing.core.PApplet.runSketch(PApplet.java:10922)
	at processing.core.PApplet.runSketch(PApplet.java:10928)
	at eu.ezytarget.processing.kotlin_template.PApplet.access$runSketch(PApplet.kt:11)
	at eu.ezytarget.processing.kotlin_template.PApplet$Companion.runInstance(PApplet.kt:202)
	at eu.ezytarget.processing.kotlin_template.Main$Companion.main(Main.kt:8)
	at eu.ezytarget.processing.kotlin_template.Main.main(Main.kt)
```

## Steps to Reproduce
1. Build Processing from commit `5b5f6eb` on macOS.
2. Create a Java project in a third-party editor.
3. Import `core.jar` to this project from the previously built `Processing.app/Contents/Java/lib`.
4. Create a Kotlin class that inherits from `processing.core.PApplet`, e.g. `MyPApplet`.
5. In the override of `settings()`, call `fullScreen()` with `PConstants.P2D` or `PConstants.P3D`.
6. Add a call to `MyPApplet().runSketch()` to the project's main method.
7. Observe that the project builds, but the applet crashes on startup.

## Your Environment
* Processing version: `master 5b5f6eb`, Alpha 1273, built with JRE 11.0.9.1
* Operating System and OS version: macOS Big Sur 11.1
* IDE: IntelliJ IDEA CE 2020.3.1

**Comment by benfry** [comment]
This isn't a Processing bug, it's an issue with how your project is set up. From a quick look, you might have a mismatched version of the JOGL libraries. (The PDE exists to avoid these kinds of errors, because they're a headache; when you're in IntelliJ, you're unfortunately on your own.)
