### ISSUE TITLE
Processing doesn't respond to "Quit" in macOS after having tried to use Art Station Tool

### ISSUE THREAD

**Issue by tokefrello** [benfry/processing4#369]
## Description

Processing doesn't respond to "Quit" in macOS after having tried to use Art Station Tool.

I installed the Art Station Tool and tried to use it/activate it, but received an error message (see the first code block at the bottom of this message). When I tried to quit Processing afterwards, nothing happens, and I received another error message (see the second code block at the bottom). I tried both the shortcut, cmd + Q, and pressing the command in the menu.

I tried the same steps multiple times, and the error occured reliably.

## Expected Behavior
I expected Processing to quit.

## Current Behavior
The "Processing" menu lights up briefly, but nothing happens.

## Steps to Reproduce

1. Install the Art Station Tool.
2. Try to activate it (you should then get the first error)
3. Try to quit (you should then get the second error).

## Your Environment

 

* Processing version: 4.0b3
* Operating System and OS version: macOS 11.6.2
* Other information: On a MacBook Pro (13-inch, M1, 2020)

## Art Station Tool error:
```
java.lang.RuntimeException: The JavaFX renderer is not in the class path.
	at processing.core.PApplet.makeGraphics(PApplet.java:2004)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:2038)
	at processing.core.PApplet.initSurface(PApplet.java:10314)
	at artstationapplication.ArtStationApplication.initSurface(Unknown Source)
	at processing.core.PApplet.runSketch(PApplet.java:10277)
	at template.tool.ArtStation.run(Unknown Source)
	at processing.app.contrib.ToolContribution.run(ToolContribution.java:124)
	at processing.app.Base.lambda$createToolItem$6(Base.java:849)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:129)
	at java.desktop/java.awt.MenuItem.processActionEvent(MenuItem.java:692)
	at java.desktop/java.awt.MenuItem.processEvent(MenuItem.java:651)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:379)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:367)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## Quit error
```
java.lang.NullPointerException: Cannot invoke "processing.core.PSurface.isStopped()" because "this.surface" is null
	at processing.core.PApplet.exit(PApplet.java:3487)
	at processing.core.ThinkDifferent.lambda$init$0(ThinkDifferent.java:62)
	at java.desktop/com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:431)
	at java.desktop/com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:420)
	at java.desktop/com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:552)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by benfry** [comment]
That's odd, I just tried it and got the (correct) message that it wasn't compatible: 

<img width="642" alt="Screen Shot 2022-01-24 at 6 45 40 AM" src="https://user-images.githubusercontent.com/1623101/150777450-1eb784e5-256a-415d-8191-e3f056212304.png">

…and was still able to quit without any trouble.

Can you make sure that you're trying File → Quit with an editor window in the foreground? Is the version of Art Station up to date? (Just in case you're using a different version than I was.) Just trying to figure out what might be going on so that we can catch it.

**Comment by tokefrello** [comment]
Sure thing! I actually seem to recall seeing the "Tool out of date" alert too, but I tried removing/re-installing Art Tool as well as Processing itself and couldn't get the alert to show – and the issue persists.

Art Station is version 1.0.0, and I can "install" it in "Add Tool..." without problems. It's greyed out in the Tools menu after I have tried activating it, but it will be available again after I force quit Processing and restart it.
