### ISSUE TITLE
OpenCV Java 245 Missing

### ISSUE THREAD

**Issue by rjua1** [benfry/processing4#468]
## Description

I am attempting to run the basic LiveCamTest example from the OpenCV library on Processing 4, but it crashes with ::
UnsatisfiedLinkError: no opencv_java245 in java.library.path:

:: then proceeds to list a variety of paths to app content and libraries folders. Inspired by [this](https://stackoverflow.com/questions/17427359/unsatisfiedlinkerror-no-opencv-java245), I pasted the missing java245.dl file in the listed locations, but none of the errors cleared. I have none of these issues when running on Processing 3. 

I am using the Video Library from Processing 4. I am running an M1 MacBook Pro OS 12.2.1

When running the afformentioned sketch, I also get these errors:
Processing video library using bundled GStreamer 1.16.2
java.lang.NoSuchFieldException: sys_paths
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at gab.opencv.OpenCV.addLibraryPath(Unknown Source)
	at gab.opencv.OpenCV.initNative(Unknown Source)
	at gab.opencv.OpenCV.<init>(Unknown Source)
	at LiveCamTest.setup(LiveCamTest.java:32)
	at processing.core.PApplet.handleDraw(PApplet.java:2142)
	at processing.awt.PSurfaceAWT$9.callDraw(PSurfaceAWT.java:1440)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:356)

**Comment by benfry** [comment]
This is an OpenCV problem; you'd need to take it up with the maintainer. If I recall correctly, the OpenCV library doesn't correctly use subfolders for the native libraries for different platforms, which breaks forward-compatibility.
