### ISSUE TITLE
fullScreen() using P2D renderer causes exception Linux (jogamp)

### ISSUE THREAD

**Issue by Buggem** [benfry/processing4#497]
## Description

Using P2D render doesn't work on Linux Intel 64-bit version of beta 8.
Code:
```
void setup() {
  fullScreen(P2D);
  
}
```
## Expected Behavior

I expect it to open Processing sketch window in complete fullScreen,
```
void setup() {
  fullScreen();
}
```
works.
## Current Behavior

I don't know whats happening but it is definitly to do with jogamp, since it says it 30 times and counting

```
Caught handled GLException: EGLGLXDrawableFactory - Could not initialize shared resources for EGLGraphicsDevice[type .egl, v0.0.0, connection :0, unitID 0, handle 0x0, owner true, ResourceToolkitLock[obj 0x459af131, isOwner true, <1acfd39d, 2afd9c2b>[count 1, qsz 0, owner <main-SharedResourceRunner>]]] on thread main-SharedResourceRunner
    [0]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.createSharedResource(EGLDrawableFactory.java:561)
    [1]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [2]: java.base/java.lang.Thread.run(Thread.java:833)
Caused[0] by GLException: Failed to created/initialize EGL display incl. fallback default: native 0x0, error 0x3001/0x3002 on thread main-SharedResourceRunner
    [0]: jogamp.opengl.egl.EGLDisplayUtil.eglGetDisplayAndInitialize(EGLDisplayUtil.java:381)
    [1]: jogamp.opengl.egl.EGLDisplayUtil.access$300(EGLDisplayUtil.java:61)
    [2]: jogamp.opengl.egl.EGLDisplayUtil$1.eglGetAndInitDisplay(EGLDisplayUtil.java:404)
    [3]: com.jogamp.nativewindow.egl.EGLGraphicsDevice.open(EGLGraphicsDevice.java:125)
    [4]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.createEGLSharedResourceImpl(EGLDrawableFactory.java:575)
    [5]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.createSharedResource(EGLDrawableFactory.java:559)
    [6]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [7]: java.base/java.lang.Thread.run(Thread.java:833)
Caught handled GLException: X11GLXDrawableFactory - Could not initialize shared resources for X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x3b105e3e, isOwner false, <5dde7b3f, 8976240>[count 0, qsz 0, owner <NULL>]]] on thread main-SharedResourceRunner
    [0]: jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:306)
    [1]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [2]: java.base/java.lang.Thread.run(Thread.java:833)
Caused[0] by GLException: main-SharedResourceRunner: Unable to create temp OpenGL context(1) on thread main-SharedResourceRunner
    [0]: jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:390)
    [1]: jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:770)
    [2]: jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:653)
    [3]: jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:591)
    [4]: jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:277)
    [5]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [6]: java.base/java.lang.Thread.run(Thread.java:833)
Caught handled GLException: EGLGLXDrawableFactory - Could not initialize shared resources for X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x3b105e3e, isOwner true, <5dde7b3f, 8976240>[count 1, qsz 0, owner <main-SharedResourceRunner>]]] on thread main-SharedResourceRunner
    [0]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.createSharedResource(EGLDrawableFactory.java:561)
    [1]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [2]: java.base/java.lang.Thread.run(Thread.java:833)
Caused[0] by GLException: Failed to created/initialize EGL display incl. fallback default: native 0x0, error 0x3001/0x3002 on thread main-SharedResourceRunner
    [0]: jogamp.opengl.egl.EGLDisplayUtil.eglGetDisplayAndInitialize(EGLDisplayUtil.java:381)
    [1]: jogamp.opengl.egl.EGLDisplayUtil.access$300(EGLDisplayUtil.java:61)
    [2]: jogamp.opengl.egl.EGLDisplayUtil$1.eglGetAndInitDisplay(EGLDisplayUtil.java:404)
    [3]: com.jogamp.nativewindow.egl.EGLGraphicsDevice.open(EGLGraphicsDevice.java:125)
    [4]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.createEGLSharedResourceImpl(EGLDrawableFactory.java:575)
    [5]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.createSharedResource(EGLDrawableFactory.java:559)
    [6]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [7]: java.base/java.lang.Thread.run(Thread.java:833)
com.jogamp.opengl.GLException: Profiles [GL4bc, GL4, GL3bc, GL3, GLES3, GL2, GLES2] not available on device X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x3b105e3e, isOwner false, <5dde7b3f, 8976240>[count 0, qsz 0, owner <NULL>]]]
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1060)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1071)
	at com.jogamp.opengl.GLProfile.getMaxProgrammable(GLProfile.java:847)
	at processing.opengl.PSurfaceJOGL.initGL(PSurfaceJOGL.java:226)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:149)
	at processing.core.PApplet.initSurface(PApplet.java:10537)
	at processing.core.PApplet.runSketch(PApplet.java:10443)
	at processing.core.PApplet.main(PApplet.java:10187)
GLException: Profiles [GL4bc, GL4, GL3bc, GL3, GLES3, GL2, GLES2] not available on device X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x3b105e3e, isOwner false, <5dde7b3f, 8976240>[count 0, qsz 0, owner <NULL>]]]
```
P.S.
I don't have any other machines at the time to test it on but there was the same result after trying 3 times.
## Steps to Reproduce

1. Get a Ubuntu 18.04 iso
2. Run my test code
3. Error message above

## Your Environment

 

* Processing version: beta 8
* Operating System and OS version: Ubuntu Bionic Beaver
* Other information:

## Possible Causes / Solutions

Removing `jogamp` for Linux?
I've heard of `jogamp` but don't know what it does so if its necessary I'm sorry for suggesting this.

**Comment by Buggem** [comment]
It doesn't seem to be able to access my display

**Comment by benfry** [comment]
Here's that code (with an extra pair of lines) running on Ubuntu 20.04:

<img width="1392" alt="Screen Shot 2022-06-16 at 12 27 04 PM" src="https://user-images.githubusercontent.com/1623101/174119795-b13578b4-ef7b-4828-b5b8-aa661d78b4ef.png">

So unfortunately that's probably something on your machine. I'd use https://discourse.processing.org/ to see if you can get help sorting out what might be going on. It looks like OpenGL isn't supported on your machine, which could be anything from installing extra drivers to making sure you're running locally and not running over SSH.

**Comment by dev01111** [comment]
Hello I am writing under my second user. I found a already asked question https://discourse.processing.org/t/sudden-opengl-problems-on-ubuntu-20-with-p2d-and-p3d/22183 and it seems updating the drivers is a fix of this problem, thanks.

**Comment by Buggem** [comment]
@benfry
Fixed! I set the openGL settings from quality to performance and it's working now, see screenshots:
![fixnvidia](https://user-images.githubusercontent.com/66670928/175720698-a4fd006d-4728-4b5e-8510-80ad56d33d61.png)
and
![test-worked](https://user-images.githubusercontent.com/66670928/175720970-3c44164f-fb30-4dc5-b39f-fe94b17ce1f1.png)
