### ISSUE TITLE
Using P2D outside the PDE

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#537]
I kind of find a solution for what I'm going to post, but since it took me over 3 hours I will post something about it anyway so it might help someone in the future.

If you want to use processing outside the PDE (like eclipse, intellij or vscode) you need to point to the core.jar.
If you want to use P2D or P3D you used to add the following jars that could be found inside the processing application:

<img width="295" alt="Screenshot 2022-08-16 at 21 35 30" src="https://user-images.githubusercontent.com/738650/184967551-5a4abe3c-072c-494a-904b-9cdf27ae573d.png">

This was at least true till Processing 3.5.4 inclusive.

If you look at how this folder (`Contents/Java/core/library`) now, then you see the following:

<img width="156" alt="Screenshot 2022-08-16 at 21 43 11" src="https://user-images.githubusercontent.com/738650/184969891-6157792c-710f-4497-96df-0ba9833e2db6.png">

If you use those files in another editor then you get the following stacktrace (you have to use P2D / P3D).

```
java.lang.UnsatisfiedLinkError: Can't load library: /Users/dw/Desktop/processing_does_not_run_anymore/natives/macosx-universal/gluegen_rt
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
        at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
        at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
        at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
        at com.jogamp.common.os.Platform$1.run(Platform.java:321)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
        at com.jogamp.nativewindow.NativeWindowFactory$1.run(NativeWindowFactory.java:239)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:236)
        at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
        at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:475)
        at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:147)
        at processing.core.PApplet.initSurface(PApplet.java:10315)
        at processing.core.PApplet.runSketch(PApplet.java:10221)
        at processing.core.PApplet.main(PApplet.java:9997)
        at processing.core.PApplet.main(PApplet.java:9969)
        at test.Test.main(Test.java:8)
```

I keep it short from here on, I found this topic:

https://forum.jogamp.org/Gluegen-rt-Can-t-find-Natives-on-Eclipse-td4038593.html

Which had the following answer:

> Hey
> 
> Try to use [jogamp-fat.jar](http://jogamp.org/deployment/archive/rc/v2.3.2/fat/jogamp-fat.jar) instead. If it doesn't work, it probably means that your version of OS X is too old. Mac OS X Lion is terribly outdated and supporting OS X in general is sometimes a nightmare, we do our best.

So I downloaded `jogamp-fat.jar` from:
https://jogamp.org/deployment/archive/rc/v2.4.0-rc-20210111/fat/

and removed everything till I only have those 2 files:

<img width="161" alt="Screenshot 2022-08-16 at 21 59 52" src="https://user-images.githubusercontent.com/738650/184974055-023d11f1-3d4c-4e75-bfa3-0f5e0f9db514.png">

Also looking at build.xml, I wonder if it wouldn't be easier if processing would use this jar instead as well. It could almost half the amount of lines in build.xml.

**Comment by matejsemancik** [comment]
I use Processing with IntelliJ & Gradle and I experience the same issue while trying to migrate my project from Processing 3.x to Processing 4.

I partially got around this by setting my `java.library.path` to where my platform native libs are located at -- such as `/Applications/Processing.app/Contents/Java/core/library/macos-x86_64` for Intel macOS.

However that does not fully solve the issue, because for example, if you want to use Processing outside the PDE with `video` library, you just can't, because the video library also uses native libs (Gstreamer) which do not come with fatjars like JOGAMP does and the `java.library.path` is already set to JOGAMP libs (and I feel like this is just wrong way to solve this).

So, my question would be -- does anyone know how to link native libs outside the PDE environment? I use Gradle to set up my build by implementing the processing jars [like this](https://github.com/matejsemancik/astral-visuals/blob/feature/processing4/buildSrc/src/main/kotlin/dev/matsem/astral/CommonDependencies.kt#L28-L48), but don't know how to configure it to pick up the native libs.

---

Edit: after some more investigation -- the `java.library.path` can contain multiple paths separated by system path separator (":" on Unix), so including more native lib paths should be fine and actually works.

To get it working, depending on your Processing installation, you can do something like this before launching your PApplet instance:

```kotlin
val processingNativeLibs = "/Applications/Processing.app/Contents/Java/core/library/macos-x86_64"
val updatedPath = "$processingNativeLibs:${System.getProperty("java.library.path")}"
System.setProperty("java.library.path", updatedPath)
```

**Comment by benfry** [comment]
Welcome to Java development… This is why the PDE exists: so that most people aren't fighting with issues like this, or that it's not their first experience.

The short answer is that you just need to include `core.jar` in your project, and add the folder for your platform to the native library path (i.e. `linux-aarch64`) by setting `-Djava.library.path=/path/to/that/folder` when running Java to launch your sketch.

This is not a Processing bug. Processing (and the PDE) exist to avoid this issue. There's a ton of code inside Processing (for running apps, exporting applications, etc) that's all there to avoid this kind of problem, because as you've found, it's confusing and a waste of time.
