### ISSUE TITLE
Processing editor will not open

### ISSUE THREAD

**Issue by renaudfv** [benfry/processing4#614]
On a new Windows 10 install with v4.1.1 opening Processing work fine once.
After rebooting nothing happens if I either try to launch the install .exe or use project files to launch it.

This is what it logs to stderr.

```
Exception in thread "main" java.lang.NoClassDefFoundError: processing/data/StringDict
	at processing.app.Platform.<clinit>(Platform.java:218)
	at processing.app.ui.Splash.getDisableHiDPI(Splash.java:135)
	at processing.app.ui.Splash.main(Splash.java:168)
Caused by: java.lang.ClassNotFoundException: processing.data.StringDict
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 3 more
```

**Comment by benfry** [comment]
Probably because Windows Defender has removed `core.jar` from the software; meaning that it's the same problem as you saw here: https://github.com/processing/processing4/issues/612
